version: "3.8"

services:
  redis:
    container_name: redis
    image: redis
    
    ports:
      - 6379:6379
    volumes: 
      - redisDB:/data

  web:
    build: ./
    environment:
          - REDISPORT=6379
          - REDISHOST=redis
    depends_on:
      - "redis"
    ports:
      - 8080:8080
volumes:
  redisDB: 